### ISSUE TITLE
storage/editResource/ for deleting a node API doesn't work

### ISSUE THREAD

**Issue by alvinrindra** [uhh-lt/autolinks#21]
e.g: 
`
{
  "before": {
    "rid": 116,
    "cid": 119,
    "metadata": {}
  }
}
`

or 

`
{
  "before": {
    "rid": 116,
    "cid": 119,
    "metadata": {}
  },
  "after": {}
}
`

**Comment by remstef** [comment]
partially fixed, depends on service and endpoint now. Issue is related to `getKey` parameter

**Comment by remstef** [comment]
fixed
